# Generated by Django 6.1 on 2026-08-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('ispaid', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('price', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='book_images/')),
            ],
        ),
    ]
