# Generated by Django 6.1 on 2026-08-11 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_audio_book_is_audiobook_alter_book_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='ispaid',
            new_name='is_paid',
        ),
    ]
