# Generated by Django 6.1 on 2026-08-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_ispaid_book_is_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='is_paid',
            new_name='ispaid',
        ),
        migrations.AddField(
            model_name='book',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
